version: '3.8'
services:
  gateway:
    build:
      context: ./
      target: development
      args:
        SERVICE_NAME: 'gateway'
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "3333:3333"
    networks:
      - backend
      - frontend
  order:
    build:
      context: ./
      target: development
      args:
        SERVICE_NAME: 'order'
    restart: always
    hostname: order
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  db:
    image: 'mongo:3.7'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./apps/db/data/db-files:/data/db"
      - "./apps/db/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure2
